name: Run Spectral lint

on:
  push:
    paths:
      - ./reference/*.yaml
  pull_request:
    paths-ignore:
      - ./reference/*.yaml

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.8.0
        with:
          file_glob: 'reference/*.yaml'
